### ISSUE TITLE
Horrendous WIFI speeds

### ISSUE THREAD

**Issue by kendreaditya** [zachs78/MacOS-XPS-9500-OpenCore#17]
Hi, 

Usually on Windows 10 I would get between 150-200 Mbps down, but when I boot into MacOS I get max speeds of 14 Mbps. I tested the speed on the "Get Help" section on the recovery menu and on a separate installation of MacOS but got the same results.

Is anyone else experiencing this? If not, could you please sure you MacOS version. I am running 10.15.7 (19H15).

**Comment by robotblox** [comment]
Hi kendreaditya,

When you use the native Killer Wi-Fi card that’s included with the XPS on Mac, you’re using itlwm drivers by the Open Intel Wireless team. 

The drivers are still early in development, and so far they only support the 802.11n standard with 2.4GHz and 5GHz running at 20MHz.

This explains the slow speeds, and the support of frequencies higher than 20MHz is planned for future releases of the driver.

The Killer card in the XPS didn’t have support previously, so the fact that the card even functions regardless of speed is a monumental accomplishment.

I would recommend keeping an eye on https://github.com/OpenIntelWireless/itlwm for future updates.
 
To increase your speeds at the moment, I would recommend getting a supported USB Wi-Fi adapter (I use the ASUS AC-53 Nano) in combination with chris1111’s Wireless-USB-Adapter drivers which can be found at the following link: https://github.com/chris1111/Wireless-USB-Adapter

(Check the compatibility list at the link above for supported adapters other than the AC-53)

Cheers!
-robotblox

**Comment by kendreaditya** [comment]
Hi robotbox,

Thank you so much for the information! I didn't realize how fortunate I was to run macOS without any required external devices. 

P.S. On a side do you also experience any lag with the trackpad? sometimes the trackpad lags and when I close the lid it goes back to normal. I tried doing some research but only case across [this](https://github.com/VoodooI2C/VoodooI2C/issues/183) which makes me think its a VoodooI2C issue.
