### ISSUE TITLE
Cursor doesn't work; Very dark screen; No internet connection

### ISSUE THREAD

**Issue by Krzysztof-Dziardziel** [zachs78/MacOS-XPS-9500-OpenCore#23]
Three issues:
- On boot, after half of the loading bar passes, the screen is VERY dark (almost impossible to see anything).
- Neither touchpad nor a USB mouse connected via WD19TB or USB-A adapter works, but I'm able to navigate the menu via keyboard.
- **(Most importantly)** There's no internet connection from WD19TB and I'm not able to set up WiFi because of the cursor issue. I'm unable to continue the installation without internet.

For USB creation I'm using:
`
# Catalina(10.15)
python ./macrecovery.py -b Mac-00BE6ED71E35EB86 -m 00000000000000000 download
`

Has anybody found a fix for any of the mentioned issues?

**Comment by Krzysztof-Dziardziel** [comment]
For ones that were having same issues:
- Very dark screen fix: Wait LONGER (up to 10 mins). Only laptop screen is so dim. If you plug the external display it's normal.
- Same thing with touchpad/mouse - you need to wait REALLY long.
- Wifi also works after waiting few more minutes after the display stops being dim.

**Comment by Krzysztof-Dziardziel** [comment]
For dark screen and mouse wait use that:
https://github.com/acidanthera/WhateverGreen

**Comment by daviddean-x** [comment]
@Krzysztof-Dziardziel 
Don't have theses issues with my 9500 everything is working eine with big sur

**Comment by Krzysztof-Dziardziel** [comment]
I wasn't able to upgrade to big sur. Had to reinstall Mojave once more - when upgrading to big sur about 1/3 of the progress bar loaded and then nothing happened. Have you changed anything between the versions?

**Comment by daviddean-x** [comment]
I had See you has different cpu, 

I had Changed a Lot zachs didn't responsed here for auch while... 
My Machines Use an 10750h processor

You could give it a try if you also have an uhd 630 graphics

**Comment by Krzysztof-Dziardziel** [comment]
I have the same GPU. I will try your solution :)
Should I do a clean install or can I just boot into system upgrade with your kexts?

**Comment by daviddean-x** [comment]
Prefer a Clean install

**Comment by Krzysztof-Dziardziel** [comment]
Thanks. I will update soon! :)
