### ISSUE TITLE
Battery Drain issue

### ISSUE THREAD

**Issue by rkzed94** [zachs78/MacOS-XPS-9500-OpenCore#5]
i tried using your EFI for XPS 15 9500 FHD version,
everything working as expected with only one main issue, battery drain. it consumed 1% battery per minute,
already tried disabling some kexts like wifi, bluetooth, and audio but still cant find the culprit yet,
any suggestion?
thankyou!

**Comment by zachs78** [comment]
It seems to be the same on my laptop. I have the charger plugged in all the time so it's not a big issue for me.
Interested to see if you can find the fix!

I did set CPUFriend to max performance but according to Intel Power Gadget, the CPU isn't a big drain though.

**Comment by rkzed94** [comment]
it seems the dgpu is not properly disabled.
changing SSDT-dGPU-Off to SSDT-NoHybGfx did the trick and increase the battery life to only drain 1% per 2-3mins.
still not great but better than before..

interestingly the fan still spinning even when the system is idle, wonder if the dgpu still not properly disabled or something else causing it to keep spinning...

**Comment by zachs78** [comment]
I changed mine to SSDT-NoHybGfx along with less aggressive CPU scaling and the drain is much lower now. Fan Is no longer spinning when idling. I've pushed the latest changes to master.

**Comment by kendreaditya** [comment]
How did you change your CPU scaling? My fans spins on medium or high (only 3 values according to dell kext) at only 40C-50C. Is there a away to manually change a fan curve?

**Comment by nikoelt** [comment]
https://github.com/stevezhengshiqi/one-key-cpufriend 

Launch Terminal
Type: bash -c "$(curl -fsSL https://raw.githubusercontent.com/stevezhengshiqi/one-key-cpufriend/master/one-key-cpufriend.sh)"

Follow instructions
