### ISSUE TITLE
Which xps?

### ISSUE THREAD

**Issue by daviddean-x** [zachs78/MacOS-XPS-9500-OpenCore#7]
Dear all,
Which XPS 9500 do you use? 13 inch or 15 inch model? Also would be some specifications at your documentation. 
There are differenzes between 13 and 15 inch models.

The S3 issue is the bedest thing, M$ know how to earn coins.

**Comment by zachs78** [comment]
If you read the description, it says XPS 15 9500. Besides, there is no 13 inch 9500. The 'x' in 9x00 denotes the size - 9300 is 13 inch, 9500 is 15, and 9700 is 17.
